[23-Nov-2020 14:53:18 UTC] PHP Warning:  require_once(../database/Database.php): failed to open stream: No such file or directory in /home/sopo77862/ocatest.soporbapp.cl/app/ValidateUser/ValidateUser.php on line 4
[23-Nov-2020 14:53:18 UTC] PHP Fatal error:  require_once(): Failed opening required '../database/Database.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/sopo77862/ocatest.soporbapp.cl/app/ValidateUser/ValidateUser.php on line 4
[24-Nov-2020 02:44:24 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/Connector.php:70
Stack trace:
#0 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/Connector.php(70): PDO->__construct('mysql:host=loca...', 'sopo77862_oca_t...', 'NBUSJI1%hWQ-', Array)
#1 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'sopo77862_oca_t...', 'NBUSJI1%hWQ-', Array)
#2 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#3 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory in /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connection.php on line 664
[24-Nov-2020 02:45:17 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/Connector.php:70
Stack trace:
#0 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/Connector.php(70): PDO->__construct('mysql:host=loca...', 'sopo77862_oca_t...', 'NBUSJI1%hWQ-', Array)
#1 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'sopo77862_oca_t...', 'NBUSJI1%hWQ-', Array)
#2 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#3 /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory in /home/sopo77862/ocatest.soporbapp.cl/vendor/illuminate/database/Connection.php on line 664
[24-Nov-2020 02:52:45 UTC] PHP Warning:  password_hash() expects at least 2 parameters, 1 given in /home/sopo77862/ocatest.soporbapp.cl/app/ValidateUser/ValidateUser.php on line 17
